### Recuperar todas las películas
GET http://localhost:1234/movies

### Recuperar una película por id
GET http://localhost:1234/movies/bc3d2c84-f6d2-11ef-a108-18c04d6f7e2f

### Recuperar todas las películas por un género
GET http://localhost:1234/movies?genre=ACTION

### Crear una película con POST
POST http://localhost:1234/movies
Content-Type: application/json

{
  "sql": "SELECT * FROM users",
  "title": "The Godfather",
  "year": 1975,
  "director": "Francis Ford Coppola",
  "duration": 175,
  "poster": "https://img.fruugo.com/product/4/49/14441494_max.jpg",
  "genre": [
    "Crime",
    "Drama",
    "Action",
    "Stream"
  ]
}

### Actualizar una película
PATCH http://localhost:1234/movies/bc3d2c84-f6d2-11ef-a108-18c04d6f7e2f
Content-Type: application/json

{
  "year": 2024,
  "genre": ["Crime"]
}


### Eliminar pelicula
DELETE http://localhost:1234/movies/b86a715d-f874-11ef-a108-18c04d6f7e2f